general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 10

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  # Ctrl+Shift+X で Vi モードをトグル
  { key = "X", mods = "Control|Shift", action = "ToggleViMode" },
  # Vi モード中に Y を押したら Copy → Viモード解除
  { key = "y", mode = "Vi|~Search", action = "Copy" },
  { key = "y", mode = "Vi|~Search", action = "ToggleViMode" },
  { key = "k", mods = "Control", chars = "\u000B" } 
]
