theme = "ayu_dark"

[editor]
true-color = true
cursorline = true
color-modes = true
auto-completion = true
auto-save = true

[keys.normal]
"C-c" = ["keep_primary_selection", "collapse_selection"]
C-s = ":w"

[keys.insert]
"C-c" = "normal_mode"

[keys.select]
"C-c" = ["normal_mode"] # , "keep_primary_selection", "collapse_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-modification-indicator", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
display-inlay-hints = true

[editor.smart-tab]
enable = true


